# Generated by Django 5.2 on 2025-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(default='Unknown Address', max_length=255)),
                ('item_name', models.CharField(default='Unknown Item', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
